# Generated by Django 4.1.1 on 2022-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('speed', models.FloatField()),
                ('description', models.TextField()),
                ('year_create', models.IntegerField()),
            ],
        ),
    ]
