# Generated by Django 4.1.1 on 2022-09-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Авто', 'verbose_name_plural': 'Авто'},
        ),
        migrations.AddField(
            model_name='auto',
            name='costs',
            field=models.IntegerField(null=True),
        ),
    ]
