# Generated by Django 4.1.1 on 2022-09-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_auto_options_auto_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='costs',
            field=models.IntegerField(null=True, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='speed',
            field=models.FloatField(verbose_name='скорость'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='title',
            field=models.CharField(max_length=20, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year_create',
            field=models.IntegerField(verbose_name='год выпуска'),
        ),
    ]
