# Generated by Django 4.1.1 on 2022-09-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_auto_costs_alter_auto_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.TextField(verbose_name='страна производитель')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
            ],
            options={
                'verbose_name': 'Страна производитель',
                'verbose_name_plural': 'Страна производитель',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.country'),
        ),
    ]
