# Generated by Django 4.1.1 on 2022-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_country_auto_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prov', models.CharField(max_length=20, verbose_name='поставщик')),
                ('adress', models.CharField(max_length=20, verbose_name='aдрес')),
                ('detail', models.TextField(verbose_name='детали')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщик',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='provider',
            field=models.ManyToManyField(to='cars.provider'),
        ),
    ]
