# Generated by Django 4.1.1 on 2022-09-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_provider_auto_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=20, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директор',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.director'),
        ),
    ]
