# Generated by Django 4.1.1 on 2022-10-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_director_country_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_model_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок комментария')),
                ('content', models.CharField(max_length=255, verbose_name='Описание комментария')),
                ('published', models.BooleanField()),
            ],
        ),
    ]
